services:
  - type: web
    name: skillfolio-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    nixpacks:
      packages:
        - wkhtmltopdf
        - fontconfig
        - freetype
        - libjpeg
        - xorg.fonts
        - xorg.libXrender
        - xorg.libXext
